#!/usr/bin/env bash
set -euo pipefail

VERSION_CODE="${VERSION_CODE:?VERSION_CODE is required}"
VERSION_NAME="${VERSION_NAME:?VERSION_NAME is required}"

IOS_DIR="$(cd "$(dirname "$0")/.." && pwd)"

cat > "${IOS_DIR}/version.generated.xcconfig" <<EOF
// Generated by CI — do not commit
CURRENT_PROJECT_VERSION = ${VERSION_CODE}
MARKETING_VERSION = ${VERSION_NAME}
EOF

printf 'VERSION_CODE=%s\nVERSION_NAME=%s\n' "${VERSION_CODE}" "${VERSION_NAME}" > "${IOS_DIR}/version.properties"

echo "iOS version set to ${VERSION_NAME} (build ${VERSION_CODE})"
