#!/usr/bin/env bash
set -euo pipefail

IOS_DIR="$(cd "$(dirname "$0")/.." && pwd)"
IOS_BUNDLE_ID="${IOS_BUNDLE_ID:-in.serveaseinnovation.serveaso}"

PROFILE_UUID=""
PROFILE_NAME=""
PROFILE_TEAM=""

if [ -f "${IOS_DIR}/.ci-provisioning-profile-uuid" ]; then
  PROFILE_UUID="$(tr -d '[:space:]' < "${IOS_DIR}/.ci-provisioning-profile-uuid")"
fi
if [ -f "${IOS_DIR}/.ci-provisioning-profile-name" ]; then
  PROFILE_NAME="$(tr -d '\n' < "${IOS_DIR}/.ci-provisioning-profile-name")"
fi
if [ -f "${IOS_DIR}/.ci-provisioning-profile-team" ]; then
  PROFILE_TEAM="$(tr -d '[:space:]' < "${IOS_DIR}/.ci-provisioning-profile-team")"
fi

: "${IOS_DEVELOPMENT_TEAM:=${PROFILE_TEAM}}"
: "${IOS_APPSTORE_PROVISIONING_PROFILE_NAME:=${PROFILE_NAME}}"

if [ -z "${IOS_DEVELOPMENT_TEAM}" ] || [ -z "${PROFILE_UUID}" ]; then
  echo "Missing signing inputs. Run ci-install-signing.sh first and set IOS_DEVELOPMENT_TEAM if needed."
  exit 1
fi

cat > "${IOS_DIR}/Signing.ci.xcconfig" <<EOF
// Generated by CI — do not commit
DEVELOPMENT_TEAM = ${IOS_DEVELOPMENT_TEAM}
CODE_SIGN_STYLE = Manual
CODE_SIGN_IDENTITY = Apple Distribution
PROVISIONING_PROFILE = ${PROFILE_UUID}
PROVISIONING_PROFILE_SPECIFIER = ${IOS_APPSTORE_PROVISIONING_PROFILE_NAME}
PRODUCT_BUNDLE_IDENTIFIER = ${IOS_BUNDLE_ID}
EOF

echo "Wrote Signing.ci.xcconfig:"
echo "  Team: ${IOS_DEVELOPMENT_TEAM}"
echo "  Bundle ID: ${IOS_BUNDLE_ID}"
echo "  Profile UUID: ${PROFILE_UUID}"
echo "  Profile name: ${IOS_APPSTORE_PROVISIONING_PROFILE_NAME}"
