#!/usr/bin/env bash
set -euo pipefail

: "${IOS_DEVELOPMENT_TEAM:?IOS_DEVELOPMENT_TEAM is required}"
: "${IOS_APPSTORE_PROVISIONING_PROFILE_NAME:?IOS_APPSTORE_PROVISIONING_PROFILE_NAME is required}"

IOS_BUNDLE_ID="${IOS_BUNDLE_ID:-in.serveaseinnovation.serveaso}"
IOS_DIR="$(cd "$(dirname "$0")/.." && pwd)"

cat > "${IOS_DIR}/Signing.ci.xcconfig" <<EOF
// Generated by CI — do not commit
DEVELOPMENT_TEAM = ${IOS_DEVELOPMENT_TEAM}
CODE_SIGN_STYLE = Manual
CODE_SIGN_IDENTITY = Apple Distribution
PROVISIONING_PROFILE_SPECIFIER = ${IOS_APPSTORE_PROVISIONING_PROFILE_NAME}
PRODUCT_BUNDLE_IDENTIFIER = ${IOS_BUNDLE_ID}
EOF

echo "Wrote Signing.ci.xcconfig for team ${IOS_DEVELOPMENT_TEAM} / ${IOS_BUNDLE_ID}"
