# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command(
  'node',
  ['-p',
   'require.resolve(
      "react-native/scripts/react_native_pods.rb",
      { paths: [process.argv[1]] }
    )',
   __dir__]
).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# React Native Firebase (static frameworks)
$RNFirebaseAsStaticFramework = true

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
else
  use_frameworks! :linkage => :static
end

target 'Serveaso' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name.start_with?('GoogleUtilities') || target.name.start_with?('Firebase') || target.name.start_with?('GoogleDataTransport') || target.name.start_with?('nanopb')
        target.build_configurations.each do |config|
          config.build_settings['DEFINES_MODULE'] = 'YES'
        end
      end
    end

    # Standard RN post install
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # 🔥 FIX FOR RCT-FOLLY + NEW XCODE
    installer.pods_project.targets.each do |target|
      if target.name == 'RCT-Folly'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
          config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
            '$(inherited)',
            'FOLLY_NO_CONFIG',
            'FOLLY_MOBILE=1',
            'FOLLY_USE_LIBCPP=1'
          ]
        end
      end
    end
  end
end
